"""Join IMD and ONSPD enrichment columns into mapping parquet."""

from __future__ import annotations

import argparse
from pathlib import Path

import duckdb
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MAPPING_PATH = REPO_ROOT / "data" / "processed" / "mapping.parquet"
DEFAULT_IMD_PATH = REPO_ROOT / "data" / "enrichment" / "imd_2025.parquet"
DEFAULT_ONSPD_PATH = REPO_ROOT / "data" / "enrichment" / "onspd_postcode_lookup.parquet"


def _normalize_postcode(series: pd.Series) -> pd.Series:
    return series.astype(str).str.upper().str.replace(" ", "", regex=False).str.strip()


def _to_upper_lookup(columns: list[str]) -> dict[str, str]:
    return {column.upper(): column for column in columns}


def _pick_column(columns: list[str], candidates: list[str], label: str) -> str:
    upper_lookup = _to_upper_lookup(columns)
    for candidate in candidates:
        key = candidate.upper()
        if key in upper_lookup:
            return upper_lookup[key]
    raise ValueError(f"Could not find {label} column. Available: {columns}")


def _read_table(path: Path) -> pd.DataFrame:
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path)

    con = duckdb.connect()
    escaped = str(path).replace("'", "''")
    return con.execute(
        f"SELECT * FROM read_csv_auto('{escaped}', header=true, sample_size=20480)"
    ).fetchdf()


def _drop_existing_enrichment_columns(mapping: pd.DataFrame) -> pd.DataFrame:
    """Drop columns generated by this script so reruns are idempotent."""

    generated_prefixes = {
        "LSOA11CD",
        "LSOA21CD",
        "LSOA_CODE",
        "LATITUDE",
        "LONGITUDE",
        "IMD_SCORE",
        "IMD_DECILE",
    }
    drop_cols = [
        col
        for col in mapping.columns
        if col.upper() in generated_prefixes
        or any(col.upper().startswith(f"{prefix}_") for prefix in generated_prefixes)
    ]
    if not drop_cols:
        return mapping
    return mapping.drop(columns=drop_cols, errors="ignore")


def load_onspd(onspd_path: Path) -> pd.DataFrame:
    onspd = _read_table(onspd_path)

    # Fast path for current canonical parquet schema.
    exact_onspd = {"postcode", "lsoa11cd", "lsoa21cd", "latitude", "longitude"}
    if exact_onspd.issubset(set(onspd.columns)):
        result = onspd[["postcode", "lsoa11cd", "lsoa21cd", "latitude", "longitude"]].copy()
        result.columns = ["POSTCODE", "LSOA11CD", "LSOA21CD", "LATITUDE", "LONGITUDE"]
        result["POSTCODE"] = _normalize_postcode(result["POSTCODE"])
        return result.drop_duplicates(subset=["POSTCODE"], keep="first")

    postcode_col = _pick_column(onspd.columns.tolist(), ["POSTCODE", "PCD7", "PCDS", "PCDS2"], "ONSPD postcode")
    lsoa11_col = _pick_column(onspd.columns.tolist(), ["LSOA11CD"], "ONSPD LSOA11 code")
    lsoa21_col = _pick_column(onspd.columns.tolist(), ["LSOA21CD"], "ONSPD LSOA21 code")
    lat_col = _pick_column(onspd.columns.tolist(), ["LAT", "LATITUDE"], "ONSPD latitude")
    lon_col = _pick_column(onspd.columns.tolist(), ["LONG", "LON", "LONGITUDE"], "ONSPD longitude")

    result = onspd[[postcode_col, lsoa11_col, lsoa21_col, lat_col, lon_col]].copy()
    result.columns = ["POSTCODE", "LSOA11CD", "LSOA21CD", "LATITUDE", "LONGITUDE"]
    result["POSTCODE"] = _normalize_postcode(result["POSTCODE"])
    result = result.drop_duplicates(subset=["POSTCODE"], keep="first")
    return result


def load_imd(imd_path: Path) -> pd.DataFrame:
    imd = _read_table(imd_path)
    columns = imd.columns.tolist()

    # Fast path for current canonical IMD parquet schema.
    exact_imd = {
        "lsoa21cd",
        "index_of_multiple_deprivation_score",
        "index_of_multiple_deprivation_decile",
    }
    if exact_imd.issubset(set(columns)):
        result = imd[
            [
                "lsoa21cd",
                "index_of_multiple_deprivation_score",
                "index_of_multiple_deprivation_decile",
            ]
        ].copy()
        result.columns = ["LSOA21CD", "IMD_SCORE", "IMD_DECILE"]
        result["LSOA21CD"] = result["LSOA21CD"].astype(str).str.strip()
        return result.drop_duplicates(subset=["LSOA21CD"], keep="first")

    lsoa_col = _pick_column(
        columns,
        [
            "LSOA21CD",
            "LSOA11CD",
            "LSOA_CODE",
            "LOWER_LAYER_SUPER_OUTPUT_AREA_LSOA_CODE",
        ],
        "IMD LSOA code",
    )

    # Keep robust fallback candidates for possible IMD source variants.
    score_col = _pick_column(
        columns,
        [
            "INDEX_OF_MULTIPLE_DEPRIVATION_SCORE",
            "INDEX OF MULTIPLE DEPRIVATION SCORE",
            "IMD_SCORE",
            "SCORE",
        ],
        "IMD score",
    )
    decile_col = _pick_column(
        columns,
        [
            "INDEX_OF_MULTIPLE_DEPRIVATION_DECILE",
            "INDEX OF MULTIPLE DEPRIVATION DECILE",
            "IMD_DECILE",
            "DECILE",
        ],
        "IMD decile",
    )

    result = imd[[lsoa_col, score_col, decile_col]].copy()
    result.columns = ["LSOA_CODE", "IMD_SCORE", "IMD_DECILE"]
    result["LSOA_CODE"] = result["LSOA_CODE"].astype(str).str.strip()
    result = result.drop_duplicates(subset=["LSOA_CODE"], keep="first")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Join IMD + ONSPD enrichment to mapping parquet")
    parser.add_argument("--mapping", default=str(DEFAULT_MAPPING_PATH))
    parser.add_argument("--imd", default=str(DEFAULT_IMD_PATH))
    parser.add_argument("--onspd", default=str(DEFAULT_ONSPD_PATH))
    parser.add_argument("--output", default=None, help="Optional output parquet path")
    args = parser.parse_args()

    mapping_path = Path(args.mapping)
    imd_path = Path(args.imd)
    onspd_path = Path(args.onspd)
    output_path = Path(args.output) if args.output else mapping_path

    if not mapping_path.exists():
        raise FileNotFoundError(f"Mapping parquet not found: {mapping_path}")
    if not imd_path.exists():
        raise FileNotFoundError(f"IMD file not found: {imd_path}")
    if not onspd_path.exists():
        raise FileNotFoundError(f"ONSPD file not found: {onspd_path}")

    mapping = pd.read_parquet(mapping_path)
    if "POSTCODE" not in mapping.columns:
        raise ValueError("Mapping parquet missing POSTCODE column")

    mapping = mapping.copy()
    mapping = _drop_existing_enrichment_columns(mapping)
    mapping["POSTCODE"] = _normalize_postcode(mapping["POSTCODE"])

    onspd = load_onspd(onspd_path)
    imd = load_imd(imd_path)

    merged = mapping.merge(onspd, on="POSTCODE", how="left")

    # Primary key path for current data is LSOA21. Fallback to LSOA11 when needed.
    if "LSOA21CD" in merged.columns and "LSOA21CD" in imd.columns:
        merged = merged.merge(imd, on="LSOA21CD", how="left")
    elif "LSOA11CD" in merged.columns and "LSOA11CD" in imd.columns:
        merged = merged.merge(imd, on="LSOA11CD", how="left")
    elif "LSOA21CD" in merged.columns and "LSOA_CODE" in imd.columns:
        merged = merged.merge(imd, left_on="LSOA21CD", right_on="LSOA_CODE", how="left")
    elif "LSOA11CD" in merged.columns and "LSOA_CODE" in imd.columns:
        merged = merged.merge(imd, left_on="LSOA11CD", right_on="LSOA_CODE", how="left")
    else:
        raise ValueError(
            "No compatible LSOA join key found between mapping+ONSPD and IMD datasets"
        )

    merged["LATITUDE"] = pd.to_numeric(merged["LATITUDE"], errors="coerce")
    merged["LONGITUDE"] = pd.to_numeric(merged["LONGITUDE"], errors="coerce")
    merged["IMD_SCORE"] = pd.to_numeric(merged["IMD_SCORE"], errors="coerce")
    merged["IMD_DECILE"] = pd.to_numeric(merged["IMD_DECILE"], errors="coerce")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    merged.to_parquet(output_path, index=False)

    print("Enrichment join complete")
    print(f"- Mapping rows: {len(mapping):,}")
    print(f"- Output path: {output_path}")
    print(f"- IMD coverage: {merged['IMD_SCORE'].notna().mean():.1%}")
    print(f"- Geo coverage: {merged['LATITUDE'].notna().mean():.1%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
